const DMA = {
'New York': ['US-NY-501', 'US-NY'],
'Los Angeles': ['US-CA-803', 'US-CA'],
'Chicago': ['US-IL-602', 'US-IL'],
'Philadelphia': ['US-PA-504', 'US-PA'],
'Boston (Manchester)': ['US-MA-506', 'US-MA'],
'San Francisco - Oakland - San Jose': ['US-CA-807', 'US-CA'],
'Dallas - Fort Worth': ['US-TX-623', 'US-TX'],
'Atlanta': ['US-GA-524', 'US-GA'],
'Houston': ['US-TX-618', 'US-TX'],
'Detroit': ['US-MI-505', 'US-MI'],
'Tampa - Saint Petersburg (Sarasota)': ['US-FL-539', 'US-FL'],
'Seattle - Tacoma': ['US-WA-819', 'US-WA'],
'Phoenix': ['US-AZ-753', 'US-AZ'],
'Cleveland': ['US-OH-510', 'US-OH'],
'Miami - Fort Lauderdale': ['US-FL-528', 'US-FL'],
'Denver': ['US-CO-751', 'US-CO'],
'Sacramento - Stockton - Modesto': ['US-CA-862', 'US-CA'],
'Portland': ['US-OR-820', 'US-OR'],
'San Diego': ['US-CA-825', 'US-CA'],
'Nashville': ['US-TN-659', 'US-TN'],
'San Antonio': ['US-TX-641', 'US-TX'],
'New Orleans': ['US-LA-622', 'US-LA'],
'Las Vegas': ['US-NV-839', 'US-NV'],
'Austin': ['US-TX-635', 'US-TX'],
'Reno': ['US-NV-811', 'US-NV'],
'Palm Springs': ['US-CA-804', 'US-CA']
}

module.exports = DMA